# fly.toml app configuration file generated for booking-rest-api on 2023-06-17T13:30:23+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "booking-rest-api"
primary_region = "cdg"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[mounts]]
  source = "uploads"
  destination = "/uploads"
