# fly.toml app configuration file generated for house-booking-api on 2023-06-17T16:38:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "house-booking-api"
primary_region = "mad"

[[mounts]]
  source = "uploads"
  destination = "/app/uploads"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
